Number = int(input("Digite um número para ver sua tabuada:  "))
print("_"*12)
print('{} x {} = {}'.format(Number, 1, Number*1))
print('{} x {} = {}'.format(Number, 2, Number*2))
print('{} x {} = {}'.format(Number, 3, Number*3))
print('{} x {} = {}'.format(Number, 4, Number*4))
print('{} x {} = {}'.format(Number, 5, Number*5))

print('{} x {} = {}'.format(Number, 6, Number*6))
print("{} x {} = {}".format(Number, 7, Number*7))
print("{} x {} = {}".format(Number, 8, Number*8))
print("{} x {} = {}".format(Number, 9, Number*9))
print("{} x {} = {}".format(Number, 10, Number*10))
print("_"*12)
